version: '3.8'

services:
  app:
    image: ghcr.io/ikmalsworld/manis:latest
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33060:3306"

volumes:
  dbdata:
  grafana-data:
