global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'laravel-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['laravel-app:80']
